# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/clayton/src/551-lab2/551-lab2.cache/wt [current_project]
set_property parent.project_path C:/Users/clayton/src/551-lab2/551-lab2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/clayton/src/551-lab2/551-lab2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/clayton/src/551-lab2/551-lab2.srcs/sources_1/new/constants.vhd
  C:/Users/clayton/src/551-lab2/551-lab2.srcs/sources_1/new/kpcsm6.vhd
  C:/Users/clayton/src/551-lab2/551-lab2.srcs/sources_1/new/square_top.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/clayton/src/551-lab2/551-lab2.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/clayton/src/551-lab2/551-lab2.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master.xdc]


synth_design -top square_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef square_top.dcp

catch { report_utilization -file square_top_utilization_synth.rpt -pb square_top_utilization_synth.pb }
