# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a200tfbg676-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/cd/src/551-team/Lab1/Lab1.cache/wt [current_project]
set_property parent.project_path /home/cd/src/551-team/Lab1/Lab1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:ac701:part0:1.1 [current_project]
read_vhdl -library xil_defaultlib /home/cd/src/551-team/Lab1/Lab1.srcs/sources_1/new/ALU.vhd
read_xdc /home/cd/src/551-team/Lab1/Nexys4_Master.xdc
set_property used_in_implementation false [get_files /home/cd/src/551-team/Lab1/Nexys4_Master.xdc]

catch { write_hwdef -file ALU.hwdef }
synth_design -top ALU -part xc7a200tfbg676-2
write_checkpoint -noxdef ALU.dcp
catch { report_utilization -file ALU_utilization_synth.rpt -pb ALU_utilization_synth.pb }
